
name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: 'Build and Push'
        runs-on: ubuntu-latest
        strategy: 
            matrix:
                node-version: [16,18,20]

        steps:
          - uses: actions/checkout@v4
          - name: setup node
            uses: actions/setup-node@v4
            with:
              node-version: '${{ matrix.node-version }}'  
              cache: 'npm'
          - run: npm install
          - run: npm run test

          - name: Generate tag
            id: tag
            run: |
              SHA=$(echo $GITHUB_SHA | head -c7)
              echo "SHA: $SHA" >> $GITHUB_OUTPUT


          - name: Build docker image
            run: docker build -t rocketseat-ci-api:${{steps.tag.outputs.SHA}} .
            




